[mypy]
ignore_missing_imports = True
implicit_optional = True

# Third-party stubs not available; relax checks on their types
[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-lmfit.*]
ignore_missing_imports = True

[mypy-impedance.*]
ignore_missing_imports = True

[mypy-thot.*]
ignore_missing_imports = True
